name: Deploy new version

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: release

      - uses: actions/setup-java@v1
        with:
          java-version: 11
          settings-path: ${{ github.workspace }}

      - run: |
          cd release
          mvn deploy -B -s ${{ github.workspace }}/settings.xml
          mvn assembly:single -B

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release/target/*.jar

      - uses: actions/checkout@v2
        with:
          ref: docs
          path: docs

      - run: |
          mv -f docs/.git .
          rm -rf docs/*
          mv .git docs
          mv -f release/target/apidocs/* docs
          cd docs
          git add
          git commit -m "Release ${{ github.event.release.tag_name }}"
          git push
