name: Deploy new version

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: release

      - uses: actions/setup-java@v1
        with:
          java-version: 11
          settings-path: ${{ github.workspace }}/release

      - run: cd release

      - name: Deploy to package registry
        run: mvn deploy -B -s settings.xml

      - run: mvn assembly:single -B

      - name: Deploy to release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/*.jar

      - uses: actions/checkout@v2
        with:
          ref: docs
          path: docs

      - name: Deploy gh-pages
        run: |
          cd ${{ github.workspace }}
          mv -f docs/.git .
          rm -rf docs/*
          mv .git docs
          mv -f release/target/apidocs/* docs
          cd docs
          git add
          git commit -m "Release ${{ github.event.release.tag_name }}"
          git push
