name: Deploy new version

on:
  release:
    types:
      - created

env:
  GITHUB_TOKEN: ${{ github.token }}
  RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11
          settings-path: ${{ github.workspace }}

      - name: Deploy to package registry
        run: mvn deploy -s ./settings.xml

      - name: Deploy javadocs to gh-pages

      - run: mvn assembly:single

      - name: Deploy to release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/*.jar
